language: python
python:
  - "2.7"
  - "3.8"
  

install:
  - pip install -r requirements.txt


script: 
  - python3 app.py
  - curl -X GET http://127.0.0.1:5000/ -d query='that movie was boring'
  
branches:
  only:
    - master
    
notifications:
  email:
    on_success: never